name: Self Test

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/self-test.yml'
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  build-npm:
    name: Build with npm
    uses: ./.github/workflows/build.yml
    with:
      package-manager: 'npm'
      node-version: '20'
      artifact-name: 'npm-build'

  build-yarn:
    name: Build with yarn
    uses: ./.github/workflows/build.yml
    with:
      package-manager: 'yarn'
      node-version: '20'
      artifact-name: 'yarn-build'

  test-npm:
    name: Test with npm
    needs: build-npm
    uses: ./.github/workflows/verify.yml
    with:
      package-manager: 'npm'
      node-version: '20'
      skip-tests: true  # No test script in current package.json
      skip-lint: true   # No lint script in current package.json

  test-yarn:
    name: Test with yarn
    needs: build-yarn
    uses: ./.github/workflows/verify.yml
    with:
      package-manager: 'yarn'
      node-version: '20'
      skip-tests: true
      skip-lint: true
