name: Test Current Code

on:
  workflow_dispatch:  # Manual trigger for testing
  push:
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  test-npm:
    name: Test with npm
    uses: ./.github/workflows/verify.yml
    with:
      package-manager: 'npm'
      node-version: '18'
      skip-tests: true  # No test script in current package.json
      skip-lint: true   # No lint script in current package.json

  test-yarn:
    name: Test with yarn
    uses: ./.github/workflows/verify.yml
    with:
      package-manager: 'yarn'
      node-version: '18'
      skip-tests: true
      skip-lint: true

  build-npm:
    name: Build with npm
    needs: test-npm
    uses: ./.github/workflows/build.yml
    with:
      package-manager: 'npm'
      node-version: '18'
      artifact-name: 'npm-build'

  build-yarn:
    name: Build with yarn
    needs: test-yarn
    uses: ./.github/workflows/build.yml
    with:
      package-manager: 'yarn'
      node-version: '18'
      artifact-name: 'yarn-build'